"""Add user model

Revision ID: 191340afbfac
Revises: 
Create Date: 2023-09-08 17:39:51.490271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191340afbfac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id_survey_', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_survey_')
    )
    op.create_table('answer',
    sa.Column('id_answer', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('id_survey', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_survey'], ['survey.id_survey_'], ),
    sa.PrimaryKeyConstraint('id_answer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('survey')
    # ### end Alembic commands ###
